spring:
  application:
    name: ao-ai-bfs
  datasource: 
    default:
       username: sysdba
       password: 3664b8215e2ec66b1f579d9b9d477f6c
#      url: jdbc:oscar://106.13.59.131:2003/aidb
       driver-class-name: com.oscar.Driver
       url-base: jdbc:oscar://
       host: 128.194.10.215
       port: 2003
       dbname: aidb
       schemaName: SCM_BFS
       url-other: 
    private:
       username: sysdba
       password: 3664b8215e2ec66b1f579d9b9d477f6c
#      url: jdbc:oscar://106.13.59.131:2003/aidb
       driver-class-name: com.oscar.Driver
       url-base: jdbc:oscar://
       host: 128.194.10.215
       port: 2003
       dbname: aidb
       schemaName: {scm_schema}
       url-other:
#  datasource:
#    username: sysdba
#    password: szoscar55
#    url: jdbc:oscar://128.194.10.215:2003/aidb
#    driver-class-name: com.oscar.Driver
  redis:
#    host: 192.168.43.19
#    port: 6379
    password: 
    cluster: 
      nodes: 192.168.43.19:6379,192.168.43.19:7000,192.168.43.19:7001
       #    - 128.194.10.223:6379
           # - 10.0.47.22:22400
           # - 10.0.47.23:22400
           #        spring.redis.cluster.nodes=127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 1000
  
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml,classpath:mybatis/*/*Mapper.xml
  type-aliases-package: gov.cnao.ao.ai.bfs.entity
server:
  port: 7112

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
app_id: edge
drap_platform.auth.identity.serviceId: edge
sqlPath: H:\sql
#sqlPath: /soft/aoai/bfs/sql
#sqlPath: /soft/aoai/20191106/bfs/sql
